export {default as  Hero} from './Hero'
export {default as  Partners} from './Partners'
export {default as  Productivity} from './Productivity'
export {default as  Network} from './Network'
export {default as  Pricing} from './Pricing'
export {default as  Footer} from './Footer'
export {default as  Faqs} from './Faqs'